<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\packages\MessageClient\MessageClient.csproj">
      <Link>MessageClient.csproj</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\apps\pong-microservice\src\PongMicroservice.csproj">
      <Aliases>PongMicroservice</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\..\apps\sample-microservice\src\src.csproj">
      <Aliases>SampleMicroservice</Aliases>
    </ProjectReference>
    <ProjectReference Include="..\..\packages\MessageClient\MessageClient.csproj" />
    <ProjectReference Include="..\..\packages\Shared.Contracts\Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.24" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.10.0" />
    <PackageReference Include="xunit" Version="2.7.0" />
  </ItemGroup>

</Project>
